import type { Metadata } from "next";
import { Questrial, Rubik } from "next/font/google";
import "./globals.css";
import Providers from "@/providers";
import Footer from "@/components/shered/Footer";

const rubik = Rubik({
    variable: "--font-Rubik",
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700", "800", "900"],
});

const questrial = Questrial({
    variable: "--font-Questrial",
    subsets: ["latin"],
    weight: ["400"],
});

export const metadata: Metadata = {
    title: "Fresh Harvests",
    // description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${rubik.className} ${questrial.variable} antialiased  text-primary-text`}>
                <div className='min-h-screen'>
                    <Providers>{children}</Providers>
                </div>
                <Footer />
            </body>
        </html>
    );
}
